from datetime import datetime
from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field


class AttachmentMetadata(BaseModel):
    filename: str
    content_type: str
    size: int
    content_id: Optional[str] = None
    is_inline: bool = False


class EmailPayload(BaseModel):
    session_id: str = Field(..., description="Unique session ID generated by Gateway")
    message_id: str = Field(..., description="Message-ID header from email")
    sender: str = Field(..., description="From address")
    recipients: List[str] = Field(..., description="To/CC/BCC recipients")
    subject: Optional[str] = None
    body_text: Optional[str] = None
    body_html: Optional[str] = None
    headers: Dict[str, str] = Field(default_factory=dict)
    attachments: List[AttachmentMetadata] = Field(default_factory=list)
    received_at: Optional[datetime] = None
    email_size: Optional[int] = None


class IngestResponse(BaseModel):
    status: str = "QUEUED"
    session_id: str
    message_id: str
    detail: str = "Email payload successfully queued for analysis"


class IngestError(BaseModel):
    status: str = "ERROR"
    session_id: Optional[str] = None
    message_id: Optional[str] = None
    detail: str
    error_code: str


class ThreatResult(BaseModel):
    threat_score: float
    verdict: str
    threat_type: Optional[str] = None
    nlp_score: Optional[float] = None
    nlp_label: Optional[str] = None
    vision_score: Optional[float] = None
    vision_label: Optional[str] = None
    url_score: Optional[float] = None
    url_verdict: Optional[str] = None
    cdr_status: Optional[str] = None
    analysis_duration_ms: Optional[int] = None
